:time_estimate: 5

= Monitoring Device and Fleet Status

_Estimated reading time: *{time_estimate} minutes*._

Objective::

Learn how to get reports of device and fleet status and health, and use field selectors to extract data from Red Hat Edge Manager.

WARNING: Work In Progress.

== Device status from Edge Manager

When you create or edit devices and other API resources from Edge Manager, you should be concerned only with a subset of their `metadata` fields and with their `spec` field.
Other fields are read-only and populated automatically at runtime.

Among these fields, the `status` field contains a lot of information gathered by the agent on the device itself or generated by Edge Manager itself.
Some of the status information surfaces in the form of icons and popups in the Edge Manager web UI, but most of them require getting a raw device resorce in YAML or JSON format.

Once you identify the exact fields and values that you are interested in, you can use standard tools such as `jq` to filter the raw device resource and show the exact information you are interested in.

All Edge Manager resource types provide some status fields, but most of the interesting ones are in device resources.
Especially because, even when you act on other resources, such as fleets and repositories, in the end you want to see, or troubleshoot, the final effect on managed devices.

== Label selectors and field selectors

As the number of edge devices grow, it becomes hard to visually check information from either the web UI or the CLI. 
And, even if you create filters using `jq` and similar tools, you may be pulling a lot of data from the Edge Manager server to your workstation.

Edge Manager provides two ways of filtering data at the server side:

* Label selectors (option `-l` in the CLI), which filter on resource labels.

* Field selectors (option `--field-selector`), which filter on a subset of the resource available fields, which are indexed by the server and vary by resource type.

Both kinds of selectors can be combined in the same command or API call.
Both kinds accept different operators and can be contatenated to filter on multiple labels and/or multiple fields.

This course shows only a small sample of the allowed combinations, you are encouraged to check the product docs and experiment with more complex filters.

The advantage of using selectors is that they reduce network traffic from the Edge Manager server to your workstation, where you can apply further processing, such as using `jq`.

== What if an update fails?

When you update the configuration of a device (which includes its system image and applications), either directly on a device or though a fleet, the agent tries to apply the new configuration only once.
If the update fails, for whatever reason, the device stays out-of-date until it gets a new configuration and its status field contain an error message stating what failed at the device itself.
In any case, the Edge Manager agent will not retry an update by itself

The following are examples of reasons an update might fail:

* The system image reference is incorrect, having a typo on the container registry server name or its image tag.

* A device does not contains credentials to access a remote container image registry server.

* A configuration tries to update a file in a read-only filesystem, for example at `/usr/lib` instead of at `/etc`.

In any of these scenarios, the solution requires changing an incorrect configuration.
But device updates might also fail when there is no configuration error, for example:

* A remote container registry server is off-line or inaccessible.

Because Edge Manager assumes managed devices might experience intermitent network issues, it leaves for the administrator to design device and fleet configurations, or the infrastructure of edge sites, to be resilient to failures.

For example, instead of pulling containers from a remote container image registy at corporate headquarters, devices could pull containers from a local image mirror at their edge location.
Alternatielly, devices could embed application containers on their bootc container image, using physically bound containers.

== Resource monitors

Edge Manager is not designed as an observability platform itself, and will not collect and display performance metrics of managed devices.
But it provides an interesting capability of monitoring essencial performance metrics and, if they fall on a configurable threshold, generate an alert.

That capability are resource monitors, which can specify a warning and a critical level for CPU, memory, and disk usage.
Each resource monitor can specify its own sampling interval, and for how long samples must be over the configured thresholds before generating an alert.

Using resource monitors you can detect situations such as a device getting its disk full, or running infinite loops consuming too much processor capability, and take corrective action.
Edge Manager itself cannot take such actions, but could be the source of events for other management platforms, such as Red Hat Ansible, which are capable of taking automatic action.

Of course, resource monitors are useful only if there is network connectivity between devices and their Edge Manager server. 
But, because they generate little network traffic, they can be useful with low-bandidth and high-latency connections.

== Events

Edge Manager provides an event resource type which offers a lightweight history of activity on the server and its managed devices.
Events are created by Edge Manager itself on conditions such as creating or chaging resources, or when there is an significant change in the status of a resource.

For example, if a managed devices stays offline for too long, meaning the Edge Manager server did not receive a "ping" from the device, it records a "disconnected" event for that device.
Failure to apply configurations, or to connect to a Git repository, also generate events.

Resource monitors also generate events when they enter warning or critical levels.

== Observability with Edge Manager

It is out of scope for this course, but Red Hat Device Edge and Red Hat Edge Manager support observability components based on the https://opentelemetry.io/[OpenTelemetry^] standard.

If you wish, you can collect performance metrics from Edge Manager servers and from managed devices themselves, by running OpenTelemetry components on the server and on managed devices.
It is up to the user providing and configuring storage and visualization infrastructure for such performance data.

== What's Next

//Mention --rendered? Guess I need to redo the app lab or the git lab to try it.

In the next section, you will create troubleshooting scenarios and practice extracting health and status information from devices and fleets using the RHEM CLI and web UI.

////
Get reports of device and fleet status and health. Status and conditions of device and fleet resources. Using field selectors to extract data from RHEM. Mention OTEL for more advanced scenarios and integration with external monitoring. Focus on OS image and system configurations; applications will be covered by the third course.
////
