:time_estimate: 12

= Lab: Troubleshoot Device and Fleet Issues

_Estimated reading time: *{time_estimate} minutes*._

Objective::

Practice troubleshooting by creating scenarios with health issues, then extract diagnostic information using RHEM tools.

WARNING: Pending Review

== Before you begin

include::ch2-fleets:partial$before-you-begin.adoc[]

== Instructions

You will configure a fleet with two devices and a disk utilization monitor.
Then you will simulate a disk full condition, on one of the devices, and detect the condition using Edge Manager.
Finally, you will resolve the disk condition and verify that Edge Manager reports the device back to healthy.

include::ch1-scale:partial$set-permissive.adoc[]

1. On your _developer machine_, verify that you have the prerequisites from the xref:ch1-scale:s3-environment-lab.adoc[first lab].
If any of the prerequisites are missing, please return to the first lab and ensure that you did not skip any step.

.. Verify that you have a clone of the course samples repository.
+
[source,console,subs="verbatim,quotes"]
--
$ *cd*
$ *ls rhde-rhem-samples*
antora.yml  config  enroll ...
--

.. Verify that you have at least two local VMs.
+
[source,console,subs="verbatim,quotes"]
--
$ *virsh list --all*
 Id   Name     State
------------------------
 1    edge-1   running
 2    edge-2   running
 3    edge-3   running
--

.. If your VMs are not running, start them, but ensuring they are booting from power on instead of resumed from saved state.
+
[source,console,subs="verbatim,quotes"]
--
$ *virsh list --all*
 Id   Name     State
-------------------------
 -    edge-1   shut off
 -    edge-2   shut off
 -    edge-3   shut off
--
+
[source,console,subs="verbatim,quotes"]
--
$ *virsh start edge-1 --force-boot*
Domain 'edge-1' started
# repeat for the remaining VMs
--

.. Give your local VMs a few moments to finish boot.
Then, log in on Edge Manager as a non-administrator and verify that there are two managed devices, which are on-line and up-to-date.
+
[source,console,subs="verbatim,quotes"]
--
$ *flightctl login -u student -p student https://servera.lab.example.com:3443*
Auto-selected organization: 00000000-0000-0000-0000-000000000000 Default
Login successful.
--
+
[source,console,subs="verbatim,quotes,attributes"]
--
$ *flightctl get device*
NAME                                                    ALIAS   OWNER            SYSTEM  UPDATED         APPLICATIONS
{edge-3-uuid-cccccccccccccccccccccccccccccccccccccc}    edge-3  Fleet/warehouse  Online  UpToDate        NoApplications
{edge-2-uuid-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb}    edge-2  Fleet/store      Online  UpToDate        NoApplications
{edge-1-uuid-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}    edge-1  <none>           Online  UpToDate        NoApplications
--

.. If you devices keep displaying as off-line for too long, it might be related to clock skew.
In that case, stop each of your local VMs and return to the beginning of this lab.
+
NOTE: Clock skew prevents a device from synchronizing with Edge Manager, and is known to happen if your ROLE classroom is stopped without first shutting down local VMs on your _develoment machine_ and later your VMs are restarted from saved state.
+
[source,console,subs="verbatim,quotes"]
--
$ *virsh destroy edge-1*
Domain 'edge-1' destroyed
# repeat for the remaining VMs
--

2. Ensure there is a `warehouse` fleet with two devices.

.. Verify that a fleet named `warehouse` already exists.
+
[source,console,subs="verbatim,quotes"]
--
$ *flightctl get fleet warehouse*
NAME            OWNER   SELECTOR                VALID
warehouse       <none>  location=warehouse      True
--

.. If it does not exist, create the fleet using the provided manifest file.
+
[source,console,subs="verbatim,quotes"]
--
$ *flightctl get fleet warehouse*
Error: response status: 404, message: Fleet of name "warehouse" not found
--
+
[source,console,subs="verbatim,quotes"]
--
$ *flightctl apply -f rhde-rhem-samples/fleet/warehouse.yaml*
warehouse.yaml: applying fleet/warehouse: 201 Created
--

.. Verify that managed devices `edge-1` and `edge-2` are members of the `warehouse` fleet.
+
[source,console,subs="verbatim,quotes,attributes"]
--
$ *flightctl get device --field-selector metadata.owner=Fleet/warehouse*
NAME                                                    ALIAS   OWNER            SYSTEM  UPDATED         APPLICATIONS
{edge-1-uuid-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}    edge-1  Fleet/warehouse  Online  UpToDate        NoApplications
{edge-2-uuid-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb}    edge-2  Fleet/warehouse  Online  UpToDate        NoApplications
--

.. If the fleet contains no devices, or only one device, join the device which is not in any fleet (or which is on a different fleet) to the warehouse fleet.
+
Edit the device to include a `location` label which matches the selector of the `warehouse` fleet.
Make such edits to `edge-1` and `edge-2` by following the example.
+
[source,console,subs="verbatim,quotes,attributes"]
--
$ *UUID=$( flightctl get device -l alias=edge-1 -o name )*
$ *flightctl edit device $UUID*
apiVersion: flightctl.io/v1beta1
kind: Device
metadata:
  ...
  labels:
    alias: edge-1
    rhel: "9.6"
    type: noapps
    *location: warehouse*
  name: {edge-1-uuid-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}
  ...
spec:
...
device/{edge-1-uuid-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa} edited
--

.. If you made any edits, wait until both `edge-1` and `edge-2` managed devices are up-to-date.
+
[source,console,subs="verbatim,quotes,attributes"]
--
$ *flightctl get device --field-selector metadata.owner=Fleet/warehouse*
NAME                                                    ALIAS   OWNER            SYSTEM  UPDATED         APPLICATIONS
{edge-1-uuid-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}    edge-1  Fleet/warehouse  Online  UpToDate        NoApplications
{edge-2-uuid-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb}    edge-2  Fleet/warehouse  Online  UpToDate        NoApplications
--

3. Add a device monitor to the fleet, using the provided manifest.
+
// It seems I cannot do it from the web UI on 1.0.2

.. Create a temporary working directory, and copy example files to it.
+
[source,console,subs="verbatim,quotes"]
--
$ *mkdir temp-monitor*
$ *cd temp-monitor*
$ **cp -r ../rhde-rhem-samples/monitor/* .**
--

.. Review the new manifest for the `warehouse` fleet.
It adds a disk space monitor, which trigger alerts when the disk is 50% and 80% full.
+
NOTE: the sampling interval and durations used in the example may not be suitable for production environments, but are intended to trigger events very quickly, so this lab doesn't take too long to complete.
+
IMPORTANT: In image mode systems, the root (`/`) directory is a bind mount.
The real root disk is mounted on the '/sysroot' directory.
Your test VMs do not set any other disk partitions, so `/var` and `/etc` are in the same root disk.
The only other disk partition is the `/boot` filesystem, which we can ignore for a disk monitor.
+
[source,console,subs="verbatim,quotes"]
--
$ *cat disk-monitor.yaml*
include::1@samples:monitor:example$disk-monitor.yaml[]
--

.. Apply the modifications to the fleet.
+
[source,console,subs="verbatim,quotes"]
--
$ *flightctl apply -f disk-monitor.yaml*
disk-monitor.yaml: applying fleet/warehouse: 200 OK
--

.. Wait until both devices in the fleet are up-to-date.
+
[source,console,subs="verbatim,quotes,attributes"]
--
$ *flightctl get device --field-selector metadata.owner=Fleet/warehouse*
NAME                                                    ALIAS   OWNER            SYSTEM  UPDATED         APPLICATIONS
{edge-1-uuid-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}    edge-1  Fleet/warehouse  Online  OutDated        NoApplications
{edge-2-uuid-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb}    edge-2  Fleet/warehouse  Online  OutDated        NoApplications
--
+
[source,console,subs="verbatim,quotes,attributes"]
--
NAME                                                    ALIAS   OWNER            SYSTEM  UPDATED         APPLICATIONS
$ *flightctl get --field-selector metadata.owner=Fleet/warehouse*
{edge-1-uuid-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}    edge-1  Fleet/warehouse  Online  UpToDate        NoApplications
{edge-2-uuid-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb}    edge-2  Fleet/warehouse  Online  UpToDate        NoApplications
--
+
The `OnLine` status ont he `SYSTEM` column, in the previous command, indicates that there are no monitors triggering alerts.

.. To view the detailed status of each monitor, you must use either the YAML or JSON output of a managed device.
The following `jq` filter shows only the status of monitors, for a shorter and more manageable output.
+
[source,console,subs="verbatim,quotes"]
--
$ *UUID=$( flightctl get device -l alias=edge-2 -o name )*
$ *flightctl get dev $UUID -o json | jq '.status.resources'*
{
  "cpu": "Healthy",
  "disk": "Healthy",
  "memory": "Healthy"
}
--

4. Fill in the disk of one of the devices to trigger a degraded state in one of the devices.

.. Open a new terminal window, and start an SSH on the `edge-2` VM/managed device.
Keep it open as you will alternate between that terminal and the terminal running the Edge Manager CLI.
+
[source,console,subs="verbatim,quotes"]
--
$ *ssh -i ../temp-enroll/edge-key -p 8222 core@127.0.0.1*
Last login: Wed Mar 18 23:25:16 2026 from 172.25.250.254
managed device: edge-2$
--

.. On your _managed device_, create a file which consumes about 50% of the available disk capacity.
+
[source,console,subs="verbatim,quotes"]
--
$ *df -h /sysroot*
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda2        19G  5.3G   14G  28% /sysroot
$ *dd if=/dev/zero of=largefile1 bs=1k count=5000000*
5000000+0 records in
5000000+0 records out
5120000000 bytes (5.1 GB, 4.8 GiB) copied, 12.741 s, 402 MB/s
$ *ls -lh largefile1*
-rw-r--r--. 1 core wheel 4.8G Mar 18 23:32 largefile1
$ *df -h /sysroot*
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda2        19G   11G  8.9G  54% /sysroot
--

.. On your _development machine_, wait a few moments and verify that the device displays a degraded status, and its disk monitor displays a warming status.
+
[source,console,subs="verbatim,quotes,attributes"]
--
$ *flightctl get device --field-selector metadata.owner=Fleet/warehouse*
NAME                                                    ALIAS   OWNER           SYSTEM          UPDATED         APPLICATIONS
{edge-2-uuid-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb}    edge-2  Fleet/warehouse *Degraded*        UpToDate        NoApplications
{edge-1-uuid-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}    edge-1  Fleet/warehouse Online          UpToDate        NoApplications
$ *flightctl get dev $UUID -o json | jq '.status.resources'*
{
  "cpu": "Healthy",
  "disk": "*Warning*",
  "memory": "Healthy"
}
--

.. Open a web browser and enter `\https://servera.lab.example.com`.
Log in as `student` using the `student` password.
Verify that the menu:Overview[] page indicates one degraded device (yellow) on its *Device status* graph.

.. Enter the menu:Fleets[] page and click the `warehouse` fleet to enter its details page.
Scroll down and verify that its its *Device status* graph also shows one degraded device.

.. Finally, enter the menu:Devices[] page and verify that the `edge-2` device displays a warning icon and a `Degraded` status.
Click the warning icon or its status messages to see a popup which states disk utilization reached a warning level.

5. Fill in the disk the same device even more, to trigger an error state.

.. On your _managed device_ create another file, which reduces avaibale capacity to less than 10% of the total disk capacity.
+
[source,console,subs="verbatim,quotes"]
--
$ *df -h /sysroot*
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda2        19G   11G  8.9G  54% /sysroot
*$ dd if=/dev/zero of=largefile2 bs=1k count=8000000*
8000000+0 records in
8000000+0 records out
8192000000 bytes (8.2 GB, 7.6 GiB) copied, 15.8843 s, 516 MB/s
$ **ls -lh largefile***
-rw-r--r--. 1 core wheel 4.8G Mar 18 23:32 largefile1
-rw-r--r--. 1 core wheel 7.7G Mar 18 23:40 largefile2
$ *df -h /sysroot*
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda2        19G   18G  1.3G  94% /sysroot
--

.. On your _development machine_, wait until the device status changes to error, and verify that its disk monitor reports a critical status.
+
[source,console,subs="verbatim,quotes,attributes"]
--
$ *flightctl get device --field-selector metadata.owner=Fleet/warehouse*
NAME                                                    ALIAS   OWNER           SYSTEM          UPDATED         APPLICATIONS
{edge-2-uuid-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb}    edge-2  Fleet/warehouse Error        UpToDate        NoApplications
{edge-1-uuid-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}    edge-1  Fleet/warehouse Online          UpToDate        NoApplications
$ *flightctl get dev $UUID -o json | jq '.status.resources'*
{
  "cpu": "Healthy",
  "disk": "Critical",
  "memory": "Healthy"
}
--

.. On the Edge Manager web UI, verify the changes on the fleet and device pages.
The device status and the circunference graphs now indicate the error and critical states.

.. You can also notice, on the menu:Events[] tab of the `edge-2` device details page, that there are warnings about disk utilization.

.. You can view events on the CLI too.
They are listed from the most recent to the oldest.
+
[source,console,subs="verbatim,quotes,attributes"]
--
$ *flightctl get event | head*
AGE             INVOLVEDOBJECT.KIND     INVOLVEDOBJECT.NAME                                     TYPE    MESSAGE
16 minutes ago  Device                  {edge-2-uuid-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb}    Warning Disk utilization has reached a critical level.
30 minutes ago  Device                  {edge-2-uuid-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb}    Warning Disk utilization has reached a warning level.
54 minutes ago  Device                  {edge-1-uuid-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}    Normal  Device has not reported any application workloads yet.
54 minutes ago  Device                  {edge-1-uuid-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}    Normal  Device's system resources are healthy.
1 hour ago      Device                  {edge-1-uuid-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}    Warning Device is disconnected (last seen more than 5 minutes ago).
1 hour ago      Device                  {edge-1-uuid-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}    Normal  Device has not reported any application workloads yet.
1 hour ago      Device                  {edge-1-uuid-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}    Normal  Device's system resources are healthy.
1 hour ago      Device                  {edge-2-uuid-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb}    Normal  Device has not reported any application workloads yet.
1 hour ago      Device                  {edge-2-uuid-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb}    Normal  Device's system resources are healthy
--

.. You filter events on fields like type (which acts like a severity) and the object they refer to.
+
[source,console,subs="verbatim,quotes,attributes"]
--
$ *flightctl get event --field-selector type=Warning | head*
AGE             INVOLVEDOBJECT.KIND     INVOLVEDOBJECT.NAME                                     TYPE    MESSAGE
21 minutes ago  Device                  {edge-2-uuid-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb}    Warning Disk utilization has reached a critical level.
35 minutes ago  Device                  {edge-2-uuid-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb}    Warning Disk utilization has reached a warning level.
1 hour ago      Device                  {edge-1-uuid-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}    Warning Device is disconnected (last seen more than 5 minutes ago).
1 hour ago      Device                  {edge-2-uuid-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb}    Warning Device is disconnected (last seen more than 5 minutes ago).
$ *flightctl get event --field-selector involvedObject.name=$UUID | head*
AGE             INVOLVEDOBJECT.KIND     INVOLVEDOBJECT.NAME                                     TYPE    MESSAGE
21 minutes ago  Device                  {edge-2-uuid-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb}    Warning Disk utilization has reached a critical level.
35 minutes ago  Device                  {edge-2-uuid-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb}    Warning Disk utilization has reached a warning level.
1 hour ago      Device                  {edge-2-uuid-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb}    Normal  Device has not reported any application workloads yet.
1 hour ago      Device                  {edge-2-uuid-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb}    Normal  Device's system resources are healthy.
1 hour ago      Device                  {edge-2-uuid-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb}    Warning Device is disconnected (last seen more than 5 minutes ago).
--

6. Clean the disk of the device to restore its healhy status.

.. On your _managed device_, remove the large files you created.
+
[source,console,subs="verbatim,quotes"]
--
$ **rm largefile***
$ *df -h  /sysroot*
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda2        19G  5.3G   14G  28% /sysroot
--

.. On your _development machine_, wait until the `edge-2` device is back to online, that is, not in degraded or error states.
Then, verify that the disk monitor is back to healthy.
+
[source,console,subs="verbatim,quotes,attributes"]
--
$ *flightctl get device --field-selector metadata.owner=Fleet/warehouse*
NAME                                                    ALIAS   OWNER           SYSTEM          UPDATED         APPLICATIONS
{edge-2-uuid-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb}    edge-2  Fleet/warehouse Online        UpToDate        NoApplications
{edge-1-uuid-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}    edge-1  Fleet/warehouse Online          UpToDate        NoApplications
$ *flightctl get dev $UUID -o json | jq '.status.resources'*
{
  "cpu": "Healthy",
  "disk": "Healthy",
  "memory": "Healthy"
}
--

You demonstrated that Edge Manager resource monitors can alert about device capacity issues and support troubleshooting workflows.
You also explored different ways of retrieving healh and status information from Edge Manager using its web UI and CLI.

== What's next

With a solid understanding of monitoring and troubleshooting devices and fleets, the next chapter explores how to deploy and manage containerized applications on your device fleets using Quadlets.

////
Create scenarios where devices have differences of configuration and health issues, and show how to get that information from RHEM. Most bullets are ideas, to be improved and detailed during course development time. Use a selector on metadata.owner to list all devices from a fleet. List all devices using a given bootc image (get devices from different fleets). Create a condition in a device (ex: disk full) and show how many devices in a fleet have a condition. Power down a device, or disconnect it from the virtual network, and verify that it's offline on RHEM. Focus on features of the RHEM CLI and webUI themselves, but find a good scenario which requires extracting raw JSON or YAML data and processing with a tool such as jq.
////
