= Managing Edge Device Fleets and Applications with Red Hat Edge Manager
:navtitle: Home

== Goal

This course teaches how to configure, manage, and monitor edge devices at scale by grouping them into device fleets with Red Hat Edge Manager and how to deploy containerized applications in devices of a fleet.

It is the second in a series of quick courses about Red Hat Edge Manager, which will consist of two courses:

. https://redhatquickcourses.github.io/rhde-rhem-devices/[Deploying Red Hat Edge Manager and Managing Edge Devices^] (pre-requisite course)

. *Managing Edge Device Fleets and Applications with Red Hat Edge Manager* (this course)

IMPORTANT: Red Hat associates must enroll using the https://training-lms.redhat.com/sso/saml/auth/rhlpint?RelayState=deeplinkoffering%3D90999535[Red Hat Learning Portal^], and Red Hat Partners must enroll using https://training-lms.redhat.com/sso/saml/auth/rhopen?RelayState=deeplinkoffering%3D90999536[Red Hat Partner Connect^]. Red Hat employees and partners must also enroll on HOL019 by following the links in the Classroom environment heading bellow.

== Objectives

On completing this course, you should be able to:

* Understand the challenges of managing edge devices at scale

* Create and manage fleets of managed devices

* Monitor and troubleshoot devices and fleets

* Configure and manage containerized applications

== Audience

* Operations-focused customer roles, who manage edge devices, but are not usually in-person at edge sites:

  ** System Administrations (IT and OT)

  ** Site Reliability Engineers (SREs)

  ** Platform Engineers and DevOps Engineers

* Red Hat and Partner roles that perform demonstrations, PoC and PoV of Red Hat Edge Manager as part of a sales motion, such as Solutions Architects.

* Red Hat and Partner roles that implement and support Red Hat Edge Manager on customers, such as Services Consultants, Technical Account Managers, and Customer Support Engineers.

== Prerequisites

This course assumes that you have the following experience:

* Having completed https://redhatquickcourses.github.io/rhde-rhem-devices/[Deploying Red Hat Edge Manager and Managing Edge Devices^] or having equivalent skills.

* Familiarity with RHEL system administration, to the level of RHCSA (Red Hat Certified System Administrator) or equivalent knowledge.

* Familiarity with Linux container tools, such as Podman, and technologies compatible with Open Container Initiative (OCI) specifications, such as container registries.

* Familiarity with image mode for RHEL, especially building bootc container images and provisioning and updating image mode systems.

It is recommended that learners already possess skills from the https://redhatquickcourses.github.io/rhde-bootc-build/[Image Mode with Red Hat Device Edge quick course series^].

Notice that no prior knowledge about Kubernetes and OpenShift is assumed or required.

== Classroom environment

You can perform all activities in this course using the virtual classroom lab from HOL019: Image Mode with Red Hat Device Edge Quick Course Series, in the Red Hat Online Learning Environment (ROLE), which is shared with the quick courses about image mode with Red Hat Device Edge and will be updated in the future to better support Red Hat Edge Manager and other Red Hat Device Edge training.

NOTE:	The Red Hat Edge Manager quick courses use ROLE for their virtual classroom labs only, and hosts course materials outside of ROLE, as GitHub pages. 

=== For Red Hat associates and partners

If you are a Red Hat associate or partner, you must first enroll in the virtual classroom lab, by using one of the following links:

* https://training-lms.redhat.com/sso/saml/auth/rhlpint?RelayState=deeplinkoffering=84932767[HOL019 for Red Hat associates^] on the Red Hat Learning Portal
* https://training-lms.redhat.com/sso/saml/auth/rhopen?RelayState=deeplinkoffering=84932768[HOL019 for Red Hat partners^] on Red Hat Partner Connect

After you enroll to HOL019 once, you can use the following links for subsequent access to the virtual classroom lab directly on Red Hat Online Learning (ROLE):

* https://role.rhu.redhat.com/rol-rhu/app/courses/hol019-10.0/[HOL019 for Red Hat associates^] on ROLE
* https://rol.redhat.com/rol/app/courses/hol019-10.0/[HOL019 for Red Hat partners^] on ROLE

=== For Red Hat customers

If you are a Red Hat customer with a *Red Hat Learning Subscription*, you can use the following link to access the virtual classroom lab on Red Hat Online Learning (ROLE):

* https://rol.redhat.com/rol/app/courses/hol019-10.0/[HOL019 for Red Hat customers^] with a *Red Hat Learning Subscription*.

=== For all learners

After you enter HOL019 on ROLE, follow the instructions there to create a new course classroom lab and access its virtual machines (VMs).
If you already created a HOL019 classroom for another image mode with Red Hat Device Edge quick course, you can continue using the same classroom lab.

Be aware that ROLE classrooms have timers after which classroom labs are stopped and deleted, to conserve compute resources.
If you plan to use the same classroom lab for multiple Red Hat Device Edge quick courses, do not wait too long to continue.

You do not need to use the same classroom for multiple courses: each course provides step-by-step instructions to start from either a new classroom lab or to continue from an existing classroom lab.

You will follow this quick course by alternating between two browser windows: one to navigate quick course materials, such as this page; and another to access the virtual classroom lab environment, to perform hands-on activities.

If you can provision your own RHEL servers or VMs, it should be possible to configure all that is required for the hands-on activities by using a https://developers.redhat.com/products/rhel/download[free subscription^] from the https://developers.redhat.com/about[Red Hat Developer Program^], which gives access to RHEL installation media and RHEL package repositories.

=== About Red Hat Online Learning (ROLE) and Red Hat Learning Subscription

The Red Hat Online Learning (ROLE) website provides https://www.redhat.com/en/services/training-and-certification[Red Hat Training and Certification^] course materials and their virtual classroom labs.
You must be enrolled in a Red Hat Training course or subscription to have access to ROLE as a Red Hat customer.

A basic https://www.redhat.com/en/services/training/learning-subscription[Red Hat Learning Subscription^] offers access to a number of Red Hat Training courses and virtual classroom lab time.
Higher subscription tiers offer additional benefits, such as Red Hat Certification Exam vouchers.

== Other sources of information about Red Hat Edge Manager

For documentation about Red Hat Edge Manager, see either its https://docs.redhat.com/en/documentation/red_hat_edge_manager/1.0[product documentation^] or its https://github.com/flightctl/flightctl/blob/main/docs/user/README.md[upstream Flight Control project documentation^].

== Author

*Fernando Lozano* +
Training Content Architect +
Red Hat - Product Portfolio Marketing & Learning

Special thanks to Ken Osborn, Sam Batschelet, and Sean O'Keffe for their support while designing and writing this course.