:time_estimate: 10

= Lab: Deploy Applications to a Fleet

_Estimated reading time: *{time_estimate} minutes*._

Objective::

Deploy a containerized application to a device fleet and observe its rollout and operation.

WARNING: Pending Review

== Before you begin

include::ch2-fleets:partial$before-you-begin.adoc[]

== Instructions

You will create a fleet that contains both inline and git configuration files, and, more importantly, a single-container application.
Then you will join a device to the new fleet, verify that the application is running, and simulate unexpected application downtime.

The inline configurations provide credentials to access a private registry.
The private registry, in turn, provides:

* A bootc container image, which is ready to run containerized application using Podman;
* An application container, which runs a simple PHP application.

The git configuration is not really necessary for this simplistic scenario; it just shows that you use multiple configuration providers on the same fleet resource.

include::ch1-scale:partial$set-permissive.adoc[]

1. On your _development machine_, verify that you have the prerequisites from the xref:ch1-scale:s3-environment-lab.adoc[first lab].
If any of the prerequisites are missing, please return to the first lab and ensure that you did not skip any steps.

.. Verify that you have a clone of the course samples repository.
+
[source,console,subs="verbatim,quotes"]
--
$ *cd*
$ *ls rhde-rhem-samples*
antora.yml  config  enroll ...
--

.. Verify that you have at least two local VMs.
+
[source,console,subs="verbatim,quotes"]
--
$ *virsh list --all*
 Id   Name     State
------------------------
 1    edge-1   running
 2    edge-2   running
 3    edge-3   running
--

.. If your VMs are not running, start them, but ensure they are booting from power on instead of resumed from saved state.
+
[source,console,subs="verbatim,quotes"]
--
$ *virsh list --all*
 Id   Name     State
-------------------------
 -    edge-1   shut off
 -    edge-2   shut off
 -    edge-3   shut off
--
+
[source,console,subs="verbatim,quotes"]
--
$ *virsh start edge-1 --force-boot*
Domain 'edge-1' started
# repeat for the remaining VMs
--

.. Give your local VMs a few moments to finish booting.
Then, log in on Edge Manager as a non-administrator and verify that there are two managed devices, which are online and up-to-date.
+
[source,console,subs="verbatim,quotes"]
--
$ *flightctl login -u student -p student https://servera.lab.example.com:3443*
Auto-selected organization: 00000000-0000-0000-0000-000000000000 Default
Login successful.
--
+
[source,console,subs="verbatim,quotes,attributes"]
--
$ *flightctl get device*
NAME                                                    ALIAS   OWNER            SYSTEM  UPDATED         APPLICATIONS
{edge-3-uuid-cccccccccccccccccccccccccccccccccccccc}    edge-3  Fleet/store      Online  UpToDate        NoApplications
{edge-2-uuid-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb}    edge-2  Fleet/warehouse  Online  UpToDate        NoApplications
{edge-1-uuid-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}    edge-1  Fleet/warehouse  Online  UpToDate        NoApplications
--

.. If you devices keep displaying as offline for too long, it might be related to clock skew.
In that case, stop each of your local VMs and return to the beginning of this lab.
+
NOTE: Clock skew prevents a device from synchronizing with Edge Manager, and is known to happen if your ROLE classroom is stopped without first shutting down local VMs on your _development machine_ and later your VMs are restarted from saved state.
+
[source,console,subs="verbatim,quotes"]
--
$ *virsh destroy edge-1*
Domain 'edge-1' destroyed
# repeat for the remaining VMs
--

2. Build and publish a bootc container image that includes a container runtime.
+
Remember that the enrollment image, which you used at the beginning of this course, provided only a minimum RHEL system with the Edge Manager agent.
That image did not include Podman or any other container runtime, so any attempt to run managed applications will fail unless you first update your devices to a suitable system image.

.. Create a temporary working directory, and copy example files to it.
+
[source,console,subs="verbatim,quotes"]
--
$ *mkdir temp-managedapp*
$ *cd temp-managedapp*
$ **cp -r ../rhde-rhem-samples/managedapp/* .**
--

.. Review the Containerfile.
It adds the container-tools meta-package, which includes Podman.
It also includes the qemu-guest-agent, which should resolve clock skew issues of local VMs.
+
[source,console,subs="verbatim,quotes"]
--
$ *cat Containerfile*
include::1@samples:managedapp:example$Containerfile[]
--

.. From the working directory of the enrollment image, copy some auxiliary files which you need to include in your bootc container image, such as the private registry CAs and SSH keys.
+
[source,console,subs="verbatim,quotes"]
--
$ *cp ../temp-enroll/domain.crt .*
$ *cp ../temp-enroll/edge-key.pub .*
$ *cp -r ../temp-enroll/rpms .*
--

.. Log in to the Red Hat container registry, so you can pull the RHEL 9 base bootc container and build your new bootc container image.
+
[source,console,subs="verbatim,quotes"]
--
$ *podman login registry.redhat.io*
...
Login Succeeded!
--
+
[source,console,subs="verbatim,quotes,attributes"]
--
$ *podman build -t rhem-containers .*
STEP 1/2: FROM registry.redhat.io/rhel9/rhel-bootc:9.6
...
Successfully tagged localhost/rhem-containers:latest
{rhem-containers-v1-shaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}
--

.. Log in to your private container registry and publish your new bootc container image there.
+
[source,console,subs="verbatim,quotes,attributes"]
--
$ *podman login -u student -p redhat registry.lab.example.com:5000*
Login Succeeded!
$ *skopeo copy containers-storage:localhost/rhem-containers:latest docker://registry.lab.example.com:5000/rhem-containers:v1.0*
...
Writing manifest to image destination
--

3. Build and publish a container image that contains a PHP web application.

.. Review the contents of the PHP application.
It only displays the version of its PHP runtime.
+
[source,console,subs="verbatim,quotes"]
--
$ *cat index.php*
include::1@samples:managedapp:example$index.php[]
--

.. Build and publish your application container.
+
[source,console,subs="verbatim,quotes,attributes"]
--
$ *podman build -t webapp -f Containerfile-webapp .*
STEP 1/8: FROM registry.redhat.io/ubi9/ubi
...
Successfully tagged localhost/webapp:latest
{rhem-webapp-v1-shaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}
$ *skopeo copy containers-storage:localhost/webapp:latest docker://registry.lab.example.com:5000/webapp:v1.0*
...
Writing manifest to image destination
--

4. Create a fleet that uses the new bootc container and also defines a single-container application.

.. Review the fleet manifest, which uses all three configuration providers covered in this course series, to demonstrate that you are able to mix them at your convenience.
+
[source,console,subs="verbatim,quotes"]
--
$ *cat frontend.yaml*
include::1@samples:managedapp:example$frontend.yaml[]
--

.. Create an authentication file for the private registry, and add it to the fleet configuration.
Notice it must be added in two places, because the container runtime and the bootc subsystems do NOT share the registry authentication files.
+
[source,console,subs="verbatim,quotes"]
--
$ *podman login --authfile auth.json -u student -p redhat registry.lab.example.com:5000*
Login Succeeded!
$ *AUTH_JSON=$( jq -c . auth.json )*
$ *sed -i "s|REPLACE_WITH_OSTREE_AUTH_JSON|$AUTH_JSON|" frontend.yaml*
$ *sed -i "s|REPLACE_WITH_ROOT_AUTH_JSON|$AUTH_JSON|" frontend.yaml*
--

.. Review your fleet manifest and ensure it no longer contains any `REPLACE` markers.

.. Review the repository manifest, which defines the `webapp` git repository referenced by the `frontend` fleet.
It points to the course samples repository.
+
[source,console,subs="verbatim,quotes"]
--
$ *cat webapp.yaml*
include::1@samples:managedapp:example$webapp.yaml[]
--

.. Apply the manifests to your Edge Manager server.
+
NOTE: The status of the fleet may be `Unknown` for a while, while Edge Manager fetches the configuration files from the Git repository.
+
[source,console,subs="verbatim,quotes"]
--
$ *flightctl apply -f webapp.yaml*
webapp.yaml: applying repository/webapp: 201 Created
$ *flightctl apply -f frontend.yaml*
frontend.yaml: applying fleet/frontend: 201 Created
--
+
[source,console,subs="verbatim,quotes"]
--
$ *flightctl get fleet frontend*
NAME            OWNER   SELECTOR        VALID
frontend        <none>  role=frontend   True
--

5. Join a managed device to the new fleet.

.. Edit the `edge-1` device manifest so its labels match the new fleet selector.
+
Edit any existing label with key `role`.
If there is no label with that key, add one.
Also ensure you remove any label with key `location`, to prevent the device matching multiple other fleets from previous labs.
+
[source,console,subs="verbatim,quotes,attributes"]
--
$ *UUID=$( flightctl get device -l alias=edge-1 -o name )*
$ *flightctl edit device $UUID*
apiVersion: flightctl.io/v1beta1
kind: Device
metadata:
  ...
  labels:
    alias: edge-1
    rhel: "9.6"
    type: noapps
    *role: frontend*
  name: {edge-1-uuid-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}
  ...
spec:
...
device/{edge-1-uuid-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa} edited
--

.. Wait until the device status changes to `UptoDate`.
Notice that the device now displays a `Healthy` status in the `APPLICATIONS` column, instead of `NoApplications`.
+
[source,console,subs="verbatim,quotes,attributes"]
--
$ *flightctl get device $UUID*
NAME                                                    ALIAS   OWNER           SYSTEM  UPDATED         APPLICATIONS
{edge-1-uuid-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}    edge-1  Fleet/frontend  Online  UpToDate        *Healthy*
--

.. Open another terminal and open a SSH session to your `edge-1` VM.
Verify that you get the expected "message of day"; proving that the device got the settings from the git configuration provider.
Keep that SSH session open, as you will return to it.
+
[source,console,subs="verbatim,quotes"]
--
$ *cd temp-managedapp*
$ *ssh -i ../temp-enroll/edge-key -p 8122 core@127.0.0.1*
Managed device running a containerized web app

Last login: Wed Mar 11 19:30:01 2026 from 172.25.250.254
[core@enroll ~]$
--

6. Verify the application is accessible, then simulate downtime in the application to show how Edge Manager reacts.

.. On your _development machine_, access the mock of your web application.
+
[source,console,subs="verbatim,quotes"]
--
$ *curl 127.0.0.1:8108*
Mock web app running PHP 8.0.30
--

.. On your `edge-1` VM, find the container id of the application container and stop it.
+
NOTE: Remember that the password for the `core` user is `redhat123`.
+
[source,console,subs="verbatim,quotes"]
--
$ *sudo podman ps*
CONTAINER ID  IMAGE                                      COMMAND               CREATED         STATUS         PORTS                 NAMES
*ac31d8eae297*  registry.lab.example.com:5000/webapp:v1.0  /bin/sh -c php-fp...  12 minutes ago  Up 12 minutes  0.0.0.0:80->8080/tcp  systemd-httpd-317337-app
--
+
[source,console,subs="verbatim,quotes"]
--
$ *sudo podman kill _ac31d8eae297_*
ac31d8eae297
--

.. On your _development machine_, wait until Edge Manager reports a change in application status.
+
[source,console,subs="verbatim,quotes,attributes"]
--
$ *flightctl get device $UUID*
NAME                                                    ALIAS   OWNER           SYSTEM  UPDATED         APPLICATIONS
{edge-1-uuid-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}    edge-1  Fleet/frontend  Online  UpToDate        *Error*
--

.. Verify that your web application is indeed offline.
+
[source,console,subs="verbatim,quotes"]
--
$ *curl 127.0.0.1:8108*
curl: (56) Recv failure: Connection reset by peer
--

.. After a few moments, Edge Manager restarts the container and the application status is back to healthy.
+
[source,console,subs="verbatim,quotes,attributes"]
--
$ *flightctl get device $UUID*
NAME                                                    ALIAS   OWNER           SYSTEM  UPDATED         APPLICATIONS
{edge-1-uuid-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}    edge-1  Fleet/frontend  Online  UpToDate        *Healthy*
--

.. If you wish, you can verify that the application is again accessible and a new container is running on the managed device.
You can now close the SSH session on your `edge-1` VM.

You demonstrated that Edge Manager can deploy, monitor, and keep containerized applications running on managed devices.
This gives organizations the flexibility of managing application lifecycles independently of operating systems updates, if they wish.

== What's next

Congratulations! You have completed this course and learned how to configure, manage, and monitor edge device fleets and deploy containerized applications using Red Hat Edge Manager.

////
Deploy an application in a fleet If the applications are not preloaded in a private container registry, build them from Containerfiles and publish in the private registry. Alternatively copy (mirror) the application from a public registry to the private registry and mention its Containerfile in the course samples public git repo. Observe as the application is rolled out (as part of a configuration update) to the fleet and verify the applications actually running on individual devices. In addition to check app rollout from RHEM, use podman and systemd on individual devices and show the quadlets and other specialized system units.
////
