:time_estimate: 7

= Considerations When Managing Edge Devices at Scale

_Estimated reading time: *{time_estimate} minutes*._

Objective::

Understand why edge devices are best managed as sets instead of individually and learn different approaches for managing applications in edge environments.

== Review of Red Hat Edge Manager

// Copied from https://docs.google.com/document/d/1m_6Xb4oEDi8s8NVq_nZ87OURBgsWj3j6Q09w-KbK5f8/edit?tab=t.0#heading=h.pmynb4an0o6

Managing infrastructure and applications at the edge is complex, given the edge technology landscape.
Organizations face challenges with connectivity, device management, diversity in hardware, operational management, scalability, and security.
To effectively manage fleets of edge devices, solutions must provide a simple, scalable experience that reduces costs and enhances control, security, and visibility for customers.

Red Hat Edge Manager offers a comprehensive solution for managing fleets of edge devices at scale.
It provides security-focused full lifecycle management—from deployment to decommissioning—including OS and configuration updates, workload management, and fleet-wide observability.
Built for modern, containerized environments, it simplifies device and application management, supporting image-mode Red Hat Enterprise Linux.

Edge Manager is offered in Red Hat Device Edge or with Red Hat Enterprise Linux for distributed compute.

=== Architecture of Red Hat Edge Manager

The main components of Edge Manager are its _API server_, which fronts a collection of microservices and maintains state about managed devices, and its _agent_, which runs on each managed device.

image::agent-vs-server.svg[title="Edge Manager agent (on managed devices) and Edge Manager server"]

Communication between Edge Manager agents and its API server is always secured using TLS.
Managed devices authenticate using mTLS certificate.
First, by using a shared enrollment-time certificate, and then by using a per-device certificate, which is generated at the time a device enrolls to become a managed device.

Managed devices are expected to run image mode for RHEL, that is, to be provisioned by using bootc container images.
The system images of managed devices must already include the Edge Manager agent before these devices can be enrolled.

The push-based approach of Edge Manager makes it suitable for handling edge devices with inconsistent or low-bandwidth network connectivity.
Even if the agent loses connection to its server, it can still keep its last known state and, when connection is restored, the agent can fetch any configuration change and apply it locally.

Edge Manager provides both a web UI and a CLI to perform management operations, including enrolling, configuring, and decommissioning managed devices.

Edge Manager can be deployed stand-alone on RHEL and on OpenShift, or integrated with either Red Hat Advanced Cluster Management or Red Hat Ansible Automation Platform.
In all these deployment models, Edge Manager provides a consistent set of features and APIs.

Although Edge Manager can integrate its web UI, authentication, and authorization with other management platforms, such as Advanced Cluster Management, it retains its own database of device state and offers the same management API for edge devices.

=== Managed device lifecycle

The following figure provides the lifecycle of a managed device, from the perspective of Edge Manager.

image::device-life-cycle.svg[title="Simplified conceptual lifecycle of a device managed by Edge Manager"]

First, a device must be provisioned, by installing RHEL and the Edge Manager agent using image mode.
Then, it can be enrolled into Edge Manager, and from now on it is a managed device, which can be configured and monitored by Edge Manager.

Any kind of update to a managed device (for example: operating system updates, changes to its configuration files, or application updates) are equivalent from Edge Manager's perspective.
They all mean applying a different configuration to a managed device.

At some point, the device is decommissioned, and it is neither configured nor monitored anymore, but still exists as an Edge Manager API resource until that resource is deleted.

An enrolled device contains an empty configuration, if it was enrolled as an individually managed device, or it can be configured right at enrollment time, if it joins a fleet.


=== GitOps for the operating system

Edge Manager enables GitOps-style management for edge devices by controlling three aspects of device configuration:

* The operating system image, that is, the bootc container image the device boots with.

* Operating system and application configuration files, stored on the edge device.

* Containerized applications running on the device.

Edge Manager applies these three aspects atomically, meaning that any change on the configuration of a managed device is either applied in its entirety or the device is considered outdated.

If there are multiple changes, the agent first stages all artifacts it needs on the device, including new and changed configuration files and any new container images.
Only when all content is already staged, does the agent switch to the new configuration.
Switching may require rebooting managed devices, but Edge Manager is smart enough to apply updates by just reloading system services, such as the System daemon, whenever possible.

The Edge Manager agent continuously observes the configuration of its device and detects any drift from the configuration declared in its Edge Manager server.
Upon detecting drift, the agent reconciles the local configuration, so it matches the state on its server.

Operating system configuration files may be stored either in the Edge Manager database, that is, on the device or fleet resources exposed by the Edge Manager API, or in an external Git repository.

Edge Manager API resources are declarative.
They state the desired state of a device: which bootc container image it boots, the contents of key configuration files, and the applications it runs.
You change device settings by changing the configuration stated by these API resources and then letting the agents reconcile the state on their devices.

== Managing devices as units or as fleets

You can manage devices as unique individual entities using Edge Manager, and the https://redhatquickcourses.github.io/rhde-rhem-devices/[first course^] focused on that, so learners could explore the drift and reconciliation process, and familiarize themselves with the web UI and CLI of the product.

This second course focuses on managing devices grouped in _fleets_.
All devices on a fleet boot from the same operating system image, contain the same set of managed configuration files, and run the same managed applications.

Consider that most edge locations, such as a retail store, include a potentially large number of devices that should be configured in exactly the same way, for example: multiple point-of-sale systems.
Edge Manager allows defining the required configuration only once, and then applying it to a number of devices automatically.

Edge Manager also provides templating for a fleet configuration, so it can accommodate small variations that may be required per individual device of a fleet.
Templating also provides flexibility of different approaches for fleet definitions, for example: configuring fleets that represent all devices in an edge location or configuring fleets that represent all devices of the same kind, independent of their actual locations.

== Managing devices as appliances vs. separation of concerns

You are not required to manage applications using Edge Manager.
It is a common approach to embed applications into an operating system image, so updating the bootc container image of a device updates both its operating system and its applications at once.

Many organizations, however, prefer to have different teams that manage the operating system patching from those that manage application code and their dependencies.
Packaging and running applications as containers is currently the preferred way of enabling such separation of concerns and allowing infrastructure teams manage to the operating system lifecycle independently of development teams and their application lifecycles.

Edge Manager supports such separation of concerns by explicitly managing containerized applications which it deploys and monitors on managed devices, be these devices managed individually or as members of fleets.

== What's Next

////
Now that you understand the fundamental approaches to managing edge devices and applications, the next section provides a quiz to review and assess your knowledge of Red Hat Edge Manager fundamentals from the previous course.
////

In the next section, you will prepare your classroom environment by deploying Red Hat Edge Manager, creating bootc container images, and provisioning test devices to practice the concepts learned in this course.

////
Why edge devices and edge servers are best managed as sets instead of individually (cattle vs pet) Approaches for managing applications in edge devices: The appliance approach vs separation of concerns, or managing applications as part of the OS image vs as separate entities, with their own lifecycle.
////
