:time_estimate: 5

= Quiz: Review RHEM Fundamentals

_Estimated reading time: *{time_estimate} minutes*._

Objective::

Review and assess your knowledge of Red Hat Edge Manager fundamentals and individual device management concepts.

== Interactive Assessment

////

Use this to refers to an single-page HTML application 's2-assessment.html' stored in the 'attachments' directory of the same chapter

++++
<iframe type="text/javascript" src='_attachments/s2-assessment.html' style="width: 768px; height: 732px" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" frameborder="0"></iframe>
++++

Else write questions and answers as nested lists.

////

== What's next

In the next section, you will prepare your classroom environment by deploying Red Hat Edge Manager, creating bootc container images, and provisioning test devices to practice the concepts learned in this course.

////
Review or assessment of RHEM fundamentals and individual device management, from the previous course.
////
