:time_estimate: 22

= Lab: Prepare the Classroom Environment

_Estimated reading time: *{time_estimate} minutes*._

Objective::

Set up and configure the classroom environment for practicing Red Hat Edge Manager fleet management.

WARNING: Work in Progress

== Before you begin

You need a customer portal account with access to a Red Hat Enterprise Linux (RHEL) subscription.
It could be a https://developers.redhat.com/products/rhel/download[Red Hat Developer program] free subscription, if you use the https://github.com/flightctl/flightctl-rpm[upstream packages] from the https://github.com/flightctl/flightctl[Flight Control^] project.

WARNING: Be aware that, as time passes, there might be significant differences between newer upstream releases and the supported Red Hat product releases.

IMPORTANT: The GA release of Edge Manager requires either a Red Hat Device Edge or RHEL with Edge Manager subscription and it is NOT included with the developer program individual subscription.

You need a _development machine_ running RHEL, to which you have unrestricted sudo access, and enough capacity to run a few local VMs.

You also need a _server machine_ running RHEL, to which you also have unrestricted sudo access.

Both your _development machine_ and _server machine_ require internet access to download RPM packages and container images.

If you are using the course classroom, your _development machine_ is the `workstation` VM.
Log in as the user `student` with password `student`.
From that machine, you may start SSH sessions to the `servera` VM, which is your _server_ machine, using the same user.
Alternatively, you can open a shell or a console directly on the `servera` VM.

== Instructions

You will verify that Edge Manager is installed and running on your _server machine_; that you can log in on Edge Manager from your _development machine_; and also that you have all files required to provision and enroll new managed devices, such as: a custom bootc container image, SSH keys, and a custom installation ISO.

All that should be already available, if you are contining straight from the https://redhatquickcourses.github.io/rhde-rhem-devices/[first course] without deleting and creating a new classroom environment, and you would skip most steps on this lab.
In that case, this lab also provides some cleaning intructions, so you are not impacted by left overs from the first course.

If you are starting from a new classroom environment, this lab provides step-by-step instructions to prepare all the necessary prerequisites for this course.

You can adapt the instructions in this course to any environment where you can install RPM packages, run Podman containers, and create VMs using libvirt.
With a bit more effort, you could run everything on a Windows or MacOS workstation, using a single large VM running RHEL and nested virtualization, or a few smaller VMs, but this course does *NOT* provide instructions for doing so.

This course was tested using a Red Hat Learning Environment (ROL) classroom which was originally created for another quick course series.
There was no customization for the specific needs of Edge Manager, and there was no attempt at providing all requirements to install Edge Manager in disconnected mode.

NOTE: Some of the requirements of Edge Manager can be satisfied by the existing RPM package and container image mirrors in the ROL classroom, but some of them require internet access, a valid Red Hat login, and Red Hat subscription entitlements.

If this is your first time using a ROL classroom, please refer to https://redhatquickcourses.github.io/rhde-rhem-devices/rhde-rhem-devices/1/ch1-intro/s3-classroom-lab.html[the previous course] for an introduction to the classroom environment and for more detail about prerequisite tasks such as: installing and configuring Red Hat Edge Manager, and enrolling managed devices.

include::ch1-scale:partial$set-permissive.adoc[]

1. On your _development machine_, download the sample code for this course.

.. Ensure that you are on your home directory and verify if you have the course samples repository.
+
[source,console,subs="verbatim,quotes"]
--
$ *cd*
$ *ls rhde-rhem-samples*
LICENSE  README.md  antora.yml  config  enroll  modules  webapp
--

.. If you do, enter the samples repository and update it, just in case. 
+
[source,console,subs="verbatim,quotes"]
--
$ *cd rhde-rhem-samples*
$ *git pull*
Already up to date.
$ *cd*
--

.. If you do not, clone the course samples repository.
+
[source,console,subs="verbatim,quotes"]
--
$ *cd*
$ *ls rhde-rhem-samples*
ls: cannot access 'rhde-rhem-samples': No such file or directory
--
+
[source,console,subs="verbatim,quotes"]
--
$ *git clone https://github.com/RedHatQuickCourses/rhde-rhem-samples.git*
Cloning into 'rhde-rhem-samples'...
...
--

2. Install tools for managing containers and VMs.

.. Verify that the `podman` and `skopeo` commands are available.
+
[source,console,subs="verbatim,quotes"]
--
$ *which podman*
/usr/bin/podman
$ *which skopeo*
/usr/bin/skopeo
--

.. If any of them is not, install the corresponding package.
+
[source,console,subs="verbatim,quotes"]
--
$ *which podman*
/usr/bin/which: no podman in (/home/student/.local/bin:/home/student/bin:/home/student/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin)
$ *which skopeo*
/usr/bin/which: no podman in (/home/student/.local/bin:/home/student/bin:/home/student/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin)
--
+
[source,console,subs="verbatim,quotes"]
--
$ *sudo dnf install skopeo buildah*
...
Complete!
--

.. Verify that libvirt tools are available.
+
[source,console,subs="verbatim,quotes"]
--
$ *which virsh*
/usr/bin/virsh
--

.. If they are not, install the libvirt tools and enable its QEMU socket service.
+
[source,console,subs="verbatim,quotes"]
--
$ *which virsh*
/usr/bin/which: no virsh in (/home/student/.local/bin:/home/student/bin:/home/student/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin)
--
+
[source,console,subs="verbatim,quotes"]
--
$ *sudo dnf install qemu-kvm libvirt virt-install virt-viewer*
...
Complete!
$ *sudo systemctl enable virtqemud.socket --now*
Created symlink /etc/systemd/system/multi-user.target.wants/virtqemud.socket → /usr/lib/systemd/system/virtqemud.socket.
--

.. Check that your unprivileged user can connect using the libvirt session interface.
+
[source,console,subs="verbatim,quotes"]
--
$ *virsh uri*
qemu:///session
$ *virsh nodeinfo*
CPU model:           x86_64
...
--

3. Enable access RPM packages and container images from Red Hat, over the internet.
+
NOTE: The `workstation` VM is preconfigured with access to a private mirror containing RHEL 10 packages, but it will need RHEL 9 packages to build bootc container images for edge devices that will be managed by Edge Manager.

.. Verify that your _development machine_ is registered with Red Hat.
+
[source,console,subs="verbatim,quotes"]
--
$ *sudo subscription-manager status*
...
The registered system name is: workstation
--

.. If it is not, register your _development machine_ using a valid Red Hat account, such as a free Red Hat Developer account.
+
[source,console,subs="verbatim,quotes"]
--
$ *sudo subscription-manager status*
+-------------------------------------------+
   System Status Details
+-------------------------------------------+
Overall Status: Not registered
--
+
[source,console,subs="verbatim,quotes"]
--
$ *sudo subscription-manager register*
...
The system has been registered with ID: aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee
The registered system name is: workstation
--

.. Log in on the Red Hat container registry.
+
Use the same Red Hat login that you used with subscription manager.
+
[source,console,subs="verbatim,quotes"]
--
$ *podman login registry.redhat.io*
...
Login Succeeded!
--
+
//TODO update to use the package mirror and containers in the private registry

.. Verify that you can access the bootc image builder container image.
You may get a different hash, because the container image was updated since these instructions were written.
+
[source,console,subs="verbatim,quotes"]
--
$ *skopeo inspect --format '{{.Digest}}' docker://registry.redhat.io/rhel9/bootc-image-builder:9.6*
sha256:f5e1860fae45c9d01fb612fcfad6c1d3a93e9ea4533bf01ea1c4d47ae2226580
--

.. Download the bootc image builder container image to the container storage of the root user.
+
You will run bootc image builder as root, so you must log in again on the Red Hat container registry.
+
[source,console,subs="verbatim,quotes"]
--
$ *sudo podman login registry.redhat.io*
...
Login Succeeded!
$ *podman pull docker://registry.redhat.io/rhel9/bootc-image-builder:9.6*
...
Storing signatures
a93aa271855242ac292133fb261c2132dd88859abb7edc29fb5681d30db422f2
--

4. Install the Edge Manager services on your _server machine_.

.. Open an SSH session or a terminal on your _server machine_.
Make sure your current shell is on the right machine before you proceed.
+
[source,console,subs="verbatim,quotes"]
--
$ *hostname*
servera
--

.. Verify that the Red Hat Edge Manager services are installed and active.
If they are, you can skip to *step 5*.
+
[source,console,subs="verbatim,quotes"]
--
$ *sudo rpm -q flightctl-services*
flightctl-services-1.0.2-1.el9.x86_64
$ *sudo systemctl is-active flightctl-api*
active
--

.. If they are not, install the container tools on your _server machine_.
+
[source,console,subs="verbatim,quotes"]
--
$ *sudo rpm -q flightctl-services*
package flightctl-services is not installed
$ *sudo systemctl is-active flightctl-target*
inactive
--
+
[source,console,subs="verbatim,quotes"]
--
$ *sudo dnf install podman skopeo*
...
Complete!
--

.. If you want to use packages from the upstream Flight Control project, enable its repository from EPEL.
+
[source,console,subs="verbatim,quotes"]
--
$ *sudo dnf config-manager --add-repo https://rpm.flightctl.io/flightctl-epel.repo*
Adding repo from: https://rpm.flightctl.io/flightctl-epel.repo
--
+
NOTE: In this case, there is no need to register `servera` because the Flight Control services package contains no dependencies other than a container engine (Podman) and the classroom environment contains a mirror of the RHEL 9 packages, which the `servera` VM is preconfigured to use.

.. Alternatively, register your _server machine_ with Red Hat subscription manager and log in on the Red Hat container registries as the `root` user.
+
NOTE: This requires using a Red Hat login entitled to a Red Hat Device Edge product subscription or other product subscription which provides Red Hat Edge Manager packages.
+
[source,console,subs="verbatim,quotes"]
--
$ *sudo subscription-manager register*
...
The registered system name is: servera
$ *sudo subscription-manager repos --enable edge-manager-1.0-for-rhel-9-x86_64-rpms*
Repository 'edge-manager-1.0-for-rhel-9-x86_64-rpms' is enabled for this system.
$ *sudo podman login registry.redhat.io*
...
Login Succeeded!
--

.. As a third alternative, use the offline mirror of the Red Hat Edge Manager package channel and log in on the Red Hat container registries.
+
NOTE: This still requires a valid Red Hat log in, but it could be from a free Red Hat Developer account.
+
IMPORTANT: Review this step after the classroom is updated.
+
[source,console,subs="verbatim,quotes"]
--
$ *dnf confifg-manager --add-repo http://content.example.com/rhde9.6/x86_64/dvd/edge-manager*
GRAB OUTPUT
$ *sudo podman login registry.redhat.io*
...
Login Succeeded!
--

.. Install the Edge Manager services.
+
[source,console,subs="verbatim,quotes"]
--
$ *sudo dnf install -y flightctl-services-1.0.2*
...
Complete!
--
+
NOTE: If you want to try the current latest release from either the upstream project or product, remove the version component `-1.0.2` from the package argument in the previous command.

.. Start the Edge Manager services.
+
[source,console,subs="verbatim,quotes"]
--
$ *sudo systemctl enable --now flightctl.target*
Created symlink '/etc/systemd/system/multi-user.target.wants/flightctl.target' → '/usr/lib/systemd/system/flightctl.target'.
--

.. Verify that the Edge Manager services are up and running.
+
Be patient, it may take a while until all container images required by Edge Manager are downloaded from the internet and it initializes its database and cache services.
When it is all done, it is expected that some services will display `exited` as their substatus.
+
[source,console,subs="verbatim,quotes"]
--
$ **sudo systemctl list-units 'flightctl*' --all**
  UNIT                                 LOAD   ACTIVE SUB     DESCRIPTION                                             
  flightctl-alert-exporter.service     loaded active running Flight Control Alert Exporter service
  flightctl-alertmanager-proxy.service loaded active running Flight Control Alertmanager Proxy service
  flightctl-alertmanager.service       loaded active running Flight Control Alertmanager service
  flightctl-api-init.service           loaded active exited  Flight Control API Initialization
  flightctl-api.service                loaded active running Flight Control API server
  flightctl-certs-init.service         loaded active exited  Flight Control Certificates Initialization
  flightctl-cli-artifacts-init.service loaded active exited  Flight Control CLI Artifacts Certificates Initialization
  flightctl-cli-artifacts.service      loaded active running Flight Control CLI Artifacts service
  flightctl-db-migrate.service         loaded active exited  Flight Control Database Migration service
  flightctl-db-users-init.service      loaded active exited  Flight Control Database Users Initialization
  flightctl-db-wait.service            loaded active exited  Flight Control Database Wait
  flightctl-db.service                 loaded active running PostgreSQL Database for Flightctl
  flightctl-kv.service                 loaded active running Flight Control Key Value service
  flightctl-network.service            loaded active exited  flightctl-network.service
  flightctl-pam-issuer.service         loaded active running Flight Control PAM OIDC Issuer server
  flightctl-periodic.service           loaded active running Flight Control Periodic service
  flightctl-ui-init.service            loaded active exited  Flight Control UI Initialization
  flightctl-ui.service                 loaded active running Flight Control UI
  flightctl-worker.service             loaded active running Flight Control Worker service                           
  flightctl.target                     loaded active active  Flight Control Services Group

Legend: LOAD   → Reflects whether the unit definition was properly loaded.
        ACTIVE → The high-level unit activation state, i.e. generalization of SUB.
        SUB    → The low-level unit activation state, values depend on unit type.

20 loaded units listed.
To show all installed unit files use 'systemctl list-unit-files'.
--

.. If you experience errors, or it seems that the Edge Manager services are taking too long to start, refer to the https://redhatquickcourses.github.io/rhde-rhem-devices/rhde-rhem-devices/1/ch2-deploy/s2-install-lab.html[previous course^] for troubleshooting hints.

.. Download the Edge Manager CLI package, which you will copy to your _development machine_.
+
[source,console,subs="verbatim,quotes"]
--
$ *dnf download flightctl-cli-1.0.2*
...
lightctl-cli-1.0.2-1.el9.x86_64.rpm 
--

.. Download the Edge Manager agent package, which you will also copy to your _development machine_.
+
[source,console,subs="verbatim,quotes"]
--
$ *dnf download flightctl-agent-1.0.2 flightctl-selinux-1.0.2*
...
(1/2): flightctl-agent-1.0.2-1.el9.x86_64.rpm
(2/2): flightctl-selinux-1.0.2-1.el9.noarch.rpm
--

5. Install the Edge Manager CLI on your _development machine_.

.. Verify that the `flightctl` command is availabe.
+
[source,console,subs="verbatim,quotes"]
--
$ *which flightctl*
/usr/bin/flightctl
--

.. If it is not, copy its package from your _server machine_ and install it.
+
NOTE: Even if the CLI package is built for RHEL 9, it works on RHEL 10 also because
the Edge Manager CLI is a static binary, with no dependencies on shared libraries.
+
[source,console,subs="verbatim,quotes"]
--
$ *which flightctl*
/usr/bin/which: no flightctl in (/home/student/.local/bin:/home/student/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin)
--
+
[source,console,subs="verbatim,quotes"]
--
$ **scp servera:~/flightctl-cli*rpm ~/Downloads**
GRAB OUTPUT
$ **sudo dnf install ~/Downloads/flightctl-cli*rpm**
...
Complete!
--

6. Configure users for the Edge Manager services, on the its PAM issuer container.

.. Verify that you can log in on Edge Manager, from your _development machine_, as a regular user and also as an administrator.
If you do, you can skip to *step 7*
+
IMPORTANT: If you see the prompt "Use insecure connections?" answer *N* and let the log in attempt fail.
+
[source,console,subs="verbatim,quotes"]
--
$ *flightctl login -u student -p student https://servera.lab.example.com:3443*
Auto-selected organization: 00000000-0000-0000-0000-000000000000 Default
Login successful.
$ *flightctl login -u admin -p redhat https://servera.lab.example.com:3443*
Auto-selected organization: 00000000-0000-0000-0000-000000000000 Default
Login successful.
--

.. If you cannot log in, switch to your _server machine_ and create groups which correspond to the `admin`, `operator`, and `viewer` roles.
+
[source,console,subs="verbatim,quotes"]
--
$ *sudo podman exec -i flightctl-pam-issuer groupadd flightctl-admin*
$ *sudo podman exec -i flightctl-pam-issuer groupadd flightctl-operator*
$ *sudo podman exec -i flightctl-pam-issuer groupadd flightctl-viewer*
--

.. Create a user named `student` and grant it the `operator` role.
+
[source,console,subs="verbatim,quotes"]
--
$ *sudo podman exec flightctl-pam-issuer adduser student*
$ *sudo podman exec -i flightctl-pam-issuer sh -c 'echo "student:student" | chpasswd'*
$ *sudo podman exec -i flightctl-pam-issuer usermod -aG flightctl-operator student*
--

.. Create a user named `admin` and grant it the `admin` role.
+
[source,console,subs="verbatim,quotes"]
--
$ *sudo podman exec flightctl-pam-issuer adduser admin*
$ *sudo podman exec -i flightctl-pam-issuer sh -c 'echo "admin:redhat" | chpasswd'*
$ *sudo podman exec -i flightctl-pam-issuer usermod -aG flightctl-admin admin*
--

.. Verify you have the required users and groups on the PAM issuer container.
+
[source,console,subs="verbatim,quotes"]
--
$ *sudo podman exec -i flightctl-pam-issuer groups student*
student : student flightctl-operator
$ *sudo podman exec -i flightctl-pam-issuer groups admin*
admin : admin flightctl-admin
--

.. Switch to your _development machine_ and copy the self-signed certificate of the Edge Manager server and add it to the system's trusted CA set.
+
[source,console,subs="verbatim,quotes"]
--
$ *scp servera:/etc/flightctl/pki/ca-bundle.crt ~*
ca-bundle.crt             100% 1222   128.6KB/s   00:00
$ *sudo cp ca-bundle.crt /etc/pki/ca-trust/source/anchors/*
$ *sudo update-ca-trust extract*
--

.. Verify that you can now log in on the Edge Manager server.
+
[source,console,subs="verbatim,quotes"]
--
$ *flightctl login -u admin -p redhat https://servera.lab.example.com:3443*
Auto-selected organization: 00000000-0000-0000-0000-000000000000 Default
Login successful.
--

.. Verify that the CLI can now get the server's version.
+
[source,console,subs="verbatim,quotes"]
--
$ *flightctl version*
Client Version: v1.0.2
Server Version: v1.0.2
--

7. Create an enrollment image for provisioning managed devices and enrolling them using late binding.

.. On your _development machine_, verify that you already have the enrollment ISO and SSH key to provision managed devices.
Look for files named `rhem-enroll.iso` and `edge-key` on the `temp-enroll` directory.
If you do, you can skip to *step 9*
+
[source,console,subs="verbatim,quotes"]
--
$ *cd*
$ *cd temp-enroll*
$ *ls*
Containerfile  bib-iso.sh  config.toml  config.yaml  edge-key  edge-key.pub  output  rhem-enroll.iso  virt-install.sh
--

.. If not, log in on your private registry and verify that the bootc enrollment image is available there.
If it is, you can skip to *step 8*.
+
[source,console,subs="verbatim,quotes,attributes"]
--
$ *podman login -u student -p redhat registry.lab.example.com:5000*
Login Succeeded!
$ *skopeo inspect --format '{{.Digest}}' docker://registry.lab.example.com:5000/rhem-enroll:v1.0*
{rhem-enroll-v1-shaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}
--

.. If it is not, copy example files and scripts for creating the enrollment image to a work directory.
Then make the work directory your current directory.
+
[source,console,subs="verbatim,quotes"]
--
$ *cd*
$ *cd temp-enroll*
bash: cd: temp-enroll: No such file or directory
$ *podman login -u student -p redhat registry.lab.example.com:5000*
Login Succeeded!
$ *skopeo inspect --format '{{.Digest}}' docker://registry.lab.example.com:5000/rhem-enroll:v1.0*
FATA[0000] Error parsing image name "docker://registry.lab.example.com:5000/rhem-enroll:v1.0": reading manifest v1.0 in registry.lab.example.com:5000/rhem-enroll: manifest unknown
--
+
[source,console,subs="verbatim,quotes"]
--
$ *cp -r rhde-rhem-samples/enroll temp-enroll*
$ *cd temp-enroll*
--
+
////
Trying to build from the product repos:
# RUN dnf -y config-manager --add-repo https://rpm.flightctl.io/flightctl-epel.repo && \
RUN sudo subscription-manager repos --enable edge-manager-1.0-for-rhel-9-x86_64-rpms && \
subscription-manager is operating in container mode. Use your host system to manage subscriptions.

So I need to subscribe workstation (which failed) or provide a local mirror of the repo and /etc/yum.conf.d files
student@workstation:~/temp-enroll$ sudo subscription-manager repos --enable edge-manager-1.0-for-rhel-9-x86_64-rpms
Error: 'edge-manager-1.0-for-rhel-9-x86_64-rpms' does not match a valid repository ID. Use "subscription-manager repos --list" to see valid repositories.

But it worked for servera (which is on RHEL 9) :-(

Trying with local files as a workaround
# RUN dnf -y config-manager --add-repo https://rpm.flightctl.io/flightctl-epel.repo && \
#    dnf -y install flightctl-agent-1.0.2 && \
ADD rpms /tmp
RUN ls /tmp/*rpm
RUN dnf -y install /tmp/flightctl*.rpm && \
    dnf clean all && \
////

.. Copy the agent package from your _server machine_, so you can include it on device images.
+
[source,console,subs="verbatim,quotes"]
--
$ *mkdir rpms*
$ **scp servera:~/flightctl-{agent,selinux}*rpm rpms**
flightctl-agent-1.0.2-1.el9.x86_64.rpm
flightctl-selinux-1.0.2-1.el9.x86_64.rpm
--

.. Review the `Containerfile` that builds a minimal enrollment image.
If you need explanations about what is included in this image, please review the https://redhatquickcourses.github.io/rhde-rhem-devices/rhde-rhem-devices/1/ch3-enroll/s2-enroll-lab.html[previous course].
+
//TODO: adapt instructions for using online product packages [may not work with 1.0.0] and/or an offline mirror
+
////
Changes top the Containerfile to use offline copy of the package
FROM registry.redhat.io/rhel9/rhel-bootc:9.6
# RUN dnf -y config-manager --add-repo https://rpm.flightctl.io/flightctl-epel.repo && \
#    dnf -y install flightctl-agent-1.0.2 && \
ADD flightctl-agent-1.0.2-1.el9.x86_64.rpm /tmp
RUN dnf -y install /tmp/flightctl-agent-1.0.2 && \
    dnf clean all && \
////

.. Copy the CA certificate of the private container registry.
Notice that the last argument of the `scp` command is a period, for the current directory.
+
[source,console,subs="verbatim,quotes"]
--
$ *scp student@utility:/opt/registry/certs/domain.crt .*
domain.crt
--

.. Build the bootc container image.
Notice that the `podman build` command finishes with a period.
+
[source,console,subs="verbatim,quotes,attributes"]
--
$ *podman build -t rhem-enroll .*
STEP 1/2: FROM registry.redhat.io/rhel9/rhel-bootc:9.6
...
Successfully tagged localhost/rhem-enroll:latest
{rhem-enroll-v1-shaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}
--

.. Publish the container image in the private registry.
+
[source,console,subs="verbatim,quotes,attributes"]
--
$ *podman login -u student -p redhat registry.lab.example.com:5000*
Login Succeeded!
$ *skopeo copy containers-storage:localhost/rhem-enroll:latest docker://registry.lab.example.com:5000/rhem-enroll:v1.0*
...
Writing manifest to image destination
--

8. Create an installable ISO containing the bootc container image from the previous step.

.. Pull your bootc container image to the container storage of the root user.
+
[source,console,subs="verbatim,quotes,attributes"]
--
$ *sudo podman login -u student -p redhat registry.lab.example.com:5000*
Login Succeeded!
$ *sudo podman pull registry.lab.example.com:5000/rhem-enroll:v1.0*
...
Writing manifest to image destination
{rhem-enroll-v1-shaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}
--

.. Review the `config.toml` file, which embeds a kickstart script for unattended installation of RHEL.

.. Set the initial user password in your kickstart script.
+
[source,console,subs="verbatim,quotes"]
--
$ *sed -i 's/REPLACE_WITH_PASSWD/redhat123/' config.toml*
--

.. Generate an SSH key and embed it in your kickstart script.
+
[source,console,subs="verbatim,quotes"]
--
$ *ssh-keygen -N '' -f edge-key -C 'initial key for edge devices'*
Generating public/private rsa key pair.
...
$ *SSH_PUB_KEY=$( cat edge-key.pub )*
$ *sed -i "s|REPLACE_WITH_SSH_KEY|$SSH_PUB_KEY|" config.toml*
--

.. Retrieve the enrollment configuration and certificate from Edge Manager and embed it in your kickstart script.
+
[source,console,subs="verbatim,quotes"]
--
$ *flightctl certificate request --expiration=365d --output=embedded > config.yaml*
Creating new ECDSA key pair and writing to "client-enrollment.key".
Submitting certificate signing request "client-enrollment-ddbfd221"... success.
Waiting for certificate to be approved and issued.... success.
$ *sed -i -e '/REPLACE_WITH_CONFIG_YAML/r config.yaml' -e '/REPLACE_WITH_CONFIG_YAML/d' config.toml*
--

.. Review your `config.toml` file to be sure that all `REPLACE_WITH` markers are gone.

.. Create a temporary directory and use the provided script to invoke bootc image builder to produce an installable ISO image.
Use your Red Hat login to access the Red Hat registry as the `root` user.
+
[source,console,subs="verbatim,quotes"]
--
$ *mkdir output*
$ *bash bib-iso.sh*
...
Build complete!
Results saved in .
--

.. Copy the generated ISO image file to a more recognizable name, outside the temporary directory.
+
[source,console,subs="verbatim,quotes"]
--
$ *cp output/bootiso/install.iso rhem-enroll.iso*
--

9. Provision and enroll two VMs which stand-in for managed devices.
+
NOTE: If you need help understand and troubleshooting managed device enrollment, please refer to the https://redhatquickcourses.github.io/rhde-rhem-devices/rhde-rhem-devices/1/ch3-enroll/s2-enroll-lab.html[first course^].

.. Verify that there are no managed devices in Edge Manager.
+
[source,console,subs="verbatim,quotes"]
--
$ *flightctl get device*
NAME    ALIAS   OWNER   SYSTEM  UPDATED APPLICATIONS
--

.. If there are any devices, decomission and delete each of them by running the following commands.
+
NOTE: This and the next substeps ensure that labs from this course labs are not impacted by left overs from labs of the previous course.
+
[source,console,subs="verbatim,quotes"]
--
$ *flightctl decomission _device-UUID_*
GRAB OUTPUT
$ *flightctl delete device _device-UUID_*
GRAB OUTPUT
--

.. Verify that there are no local VMs.
+
[source,console,subs="verbatim,quotes"]
--
$ *virsh list --all*
 Id   Name   State
--------------------
--

.. If there are any VMs, delete each of them by running the following commands.
+
[source,console,subs="verbatim,quotes"]
--
$ *virsh destroy _vm_*
GRAB OUTPUT
$ *virsh undefine _vm_*
GRAB OUTPUT
$ *rm ~/.local/share/libvirt/images/_vm_.qcow2*
--

.. Use the provided script to invoke `virt-install` to create a local test VM, booting it from the ISO.
+
At the end of the instalation, press kbd:[Ctrl+\]] to leave the text console of the VM and return to your host shell.
+
[source,console,subs="verbatim,quotes"]
--
$ *bash virt-install.sh 1*
Creating VM edge-1, use port 8122 for SSH.
...
Domain creation completed.
Restarting guest.
Running text console command: virsh --connect qemu:///session console edge-1
Connected to domain 'edge-1'
Escape character is ^] (Ctrl + ])
--
+
////
Got AGAIN the SELinux error with passt. As if I had to fix labels everytime I create a classroom? Could it be the cloud-init settings?
No, fix-files didn't fix it???
Every reboot fix-files -v check shows a new list of files to relabel, but I get the same avc :-(
////

.. Verify that there is a pending enrollment request.
+
[source,console,subs="verbatim,quotes,attributes"]
--
$ *flightctl get enrollmentrequest*
NAME                                                    APPROVAL        APPROVER        APPROVED LABELS
{edge-1-uuid-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}    Pending         <none>
--

.. Approve the enrollment request, setting a few labels on the managed device.
+
Be sure you use the same UUID you got from the previous step to refer to the enrollment request.
+
[source,console,subs="verbatim,quotes,attributes"]
--
$ *flightctl approve enrollmentrequest -l alias=edge-2 -l rhel=9.6 -l type=noapps _{edge-1-uuid-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}_*
--
+
// There's no output from the approve command

.. Verify that the enrollment request now is set to approved and there is a managed device.
+
[source,console,subs="verbatim,quotes,attributes"]
--
$ *flightctl get enrollmentrequest*
NAME                                                    APPROVAL        APPROVER        APPROVED LABELS
{edge-1-uuid-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}    Approved        admin           alias=edge-1,rhel=9.6,type=noapps
$ *flightctl get device -o wide*
NAME                                                    ALIAS   OWNER   SYSTEM  UPDATED         APPLICATIONS    LABELS
{edge-1-uuid-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}    edge-1  <none>  Online  OutOfDate       NoApplications  alias=edge-1,rhel=9.6,type=noapps
--

.. Wait a few moments while the Edge Manager agent finishes synchronizing the device with the configurations set by Edge Manager.
+
[source,console,subs="verbatim,quotes,attributes"]
--
$ *flightctl get device -o wide*
NAME                                                    ALIAS   OWNER   SYSTEM  UPDATED         APPLICATIONS    LABELS
{edge-1-uuid-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}    edge-1  <none>  Online  UpToDate        NoApplications  alias=edge-1,rhel=9.6,type=noapp
--

.. Repeat the process to create a second local test VM.
+
[source,console,subs="verbatim,quotes,attributes"]
--
$ *bash virt-install.sh 2*
Creating VM edge-2, use port 8122 for SSH.
...
Domain creation completed.
Restarting guest.
Running text console command: virsh --connect qemu:///session console edge-2
Connected to domain 'edge-2'
Escape character is ^] (Ctrl + ])
kbd:[Ctrl+\]]
--

.. Approve the enrollment of your second local test VM.
+
[source,console,subs="verbatim,quotes,attributes"]
--
$ *flightctl get enrollmentrequest*
NAME                                                    APPROVAL        APPROVER        APPROVED LABELS
{edge-2-uuid-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb}    Pending         <none>
{edge-1-uuid-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}    Approved        admin           alias=edge-1,rhel=9.6,type=noapps
--
+
[source,console,subs="verbatim,quotes,attributes"]
--
$ *flightctl approve enrollmentrequest -l alias=edge-2 -l rhel=9.6 -l type=noapps _{edge-2-uuid-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb}_*
--

.. Wait until your second managed device is `UpToDate`.
+
[source,console,subs="verbatim,quotes,attributes"]
--
$ *flightctl get device -o wide*
NAME                                                    ALIAS   OWNER   SYSTEM  UPDATED         APPLICATIONS    LABELS
{edge-1-uuid-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}    edge-1  <none>  Online  UpToDate        NoApplications  alias=edge-2,rhel=9.6,type=noapps
{edge-2-uuid-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb}    edge-2  <none>  Online  UpToDate        NoApplications  alias=edge-2,rhel=9.6,type=noapps
--

You now have a minimaly configured Edge Manager service and two local VMs which act as managed devices, that are fully provisioned and enrolled into Edge Manager.
This environment will be a starting point for the activities in the next chapters.

== What's next

With your environment prepared and test devices enrolled, the next chapter explores how to organize and manage these devices efficiently using Red Hat Edge Manager's fleet concept.

////
Prepare the classroom environment, if it is a new one. That is, learners are not continuing from the previous course on the same virtual labs. Deploy RHEM. Create sample bootc container images. Publish the bootc images in a private container registry. Create a sample ISO installation image. Create a few test VMs using virt-install. Enroll the test VMs. Application images should be preseeded in a private or public container registry.
////
